# the following commands are used for debug purposes only
FROM dpage/pgadmin4:latest

USER root
# # Update and upgrade packages before installing new ones
RUN apk update && apk upgrade && apk add --no-cache bash curl jq vim

